services:
    terminal42_assets.listener.assets:
        class: Terminal42\AssetsBundle\EventListener\AssetsListener
        arguments:
            - "%terminal42_assets.collections%"
            - "%kernel.root_dir%/../web"
